In [2]:
import numpy as np
import gym 
import random

In [3]:
env = gym.make("FrozenLake-v0")

In [7]:
action_size = env.action_space.n
state_size = env.observation_space.n

16


In [8]:
qtable = np.zeros((state_size, action_size))

In [9]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

In [12]:
#List of rewards
rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step =  0 
    done = False 
    total_rewards = 0 
    
    for step in range(max_steps):
        #Choose action in current state 
        exp_exp_tradeoff = random.uniform(0,1)
        
        #if random number is greater thhan epsilon --> exploit (take biggest Q value)
        if exp_exp_tradeoff>epsilon:
            action = np.argmax(qtable[state,:])
        else: #Explore
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        state = new_state
        if done == True: 
            break
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.47773333333333334
[[1.92969589e-01 6.21627524e-02 5.72037242e-02 6.17984146e-02]
 [1.17831315e-02 3.85045174e-02 3.36493972e-02 5.90257966e-02]
 [1.53703251e-02 2.23882768e-02 2.07664974e-02 5.31913222e-02]
 [6.74138881e-03 6.48831326e-03 1.67574241e-02 3.97402259e-02]
 [1.79715782e-01 2.64420930e-02 1.08550798e-02 6.82627480e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.61124675e-04 1.67290690e-06 4.86517364e-05 1.59391511e-10]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.76265054e-02 2.16476411e-03 1.19475217e-03 1.02076661e-01]
 [3.99040583e-02 6.51801526e-02 2.36932452e-02 3.84536646e-02]
 [5.04468764e-01 1.00162872e-03 4.17545307e-04 3.92531697e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.66816189e-02 1.36509678e-01 1.99618725e-01 4.34929282e-02]
 [1.89789526e-01 9.30702300e-01 1.10100604e-01 1.17125810e-01]
 [0.00000000e+00 0

In [13]:
env.reset()
for episode in range(5):
    state = env.reset()
    step = 0 
    done = False 
    print("****************************************************")
    print("EPISODE ", episode)
    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 47
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 83
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 41
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 43
****************************************************
EPISODE  4
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 50
